import { CommonModule } from "@angular/common";
import { NgModule } from "@angular/core";
import {
  MatButtonModule,
  MatCheckboxModule,
  MatInputModule,
  MatFormFieldModule,
  MatSidenavModule,
  MatToolbarModule,
  MatListModule,
  MatTabsModule,
  MatIconModule,
  MatCardModule,
  MatOptionModule,
  MatSelectModule,
  MatProgressSpinnerModule,
  MatDialogModule,
  MatTableModule,
  MatSortModule,
  MatRadioModule,
  MatDividerModule,
  MatChipsModule,
  MatExpansionModule,
  MatGridListModule,
  MatSlideToggleModule,
  MatPaginatorModule,
  MatButtonToggleModule,
  MatMenuModule,
  MatMenuTrigger,
  MatTooltipModule,
  MatSnackBarModule,
} from "@angular/material";
import { FormsModule, ReactiveFormsModule } from "@angular/forms";
import { FlexLayoutModule } from "@angular/flex-layout";
import { ShareModule } from "@ngx-share/core";
import { FontAwesomeModule } from "@fortawesome/angular-fontawesome";
import { NgtUniversalModule } from "@ng-toolkit/universal";
import { HttpClientModule } from "@angular/common/http";
// import { TransferHttpCacheModule } from '@nguniversal/common';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    FlexLayoutModule,
    MatInputModule,
    MatFormFieldModule,
    MatListModule,
    MatTabsModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatSortModule,
    MatRadioModule,
    MatDividerModule,
    MatChipsModule,
    MatExpansionModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatToolbarModule,
    MatPaginatorModule,
    MatButtonToggleModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatDividerModule,
    FontAwesomeModule,
    CommonModule,
    NgtUniversalModule,
  ],
  declarations: [],

  exports: [
    MatButtonModule,
    MatCheckboxModule,
    FlexLayoutModule,
    MatInputModule,
    MatFormFieldModule,
    CommonModule,
    MatListModule,
    MatTabsModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatSortModule,
    MatRadioModule,
    MatDividerModule,
    MatChipsModule,
    MatExpansionModule,
    MatGridListModule,
    MatSlideToggleModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    MatPaginatorModule,
    MatButtonToggleModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatDividerModule,
    FontAwesomeModule,
    ShareModule,
    MatToolbarModule,
    NgtUniversalModule,
  ],
  providers: [],
})
export class SharedModule {}
